spring:
  jpa.open-in-view: false
  web.resources.add-mappings: false
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/larryta
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

jasypt.encryptor.password: ${JASYPT_PASSWORD}

logging:.level:
  org.springframework.web.servlet.PageNotFound: ERROR
